### ISSUE TITLE
How to use nib cell?

### ISSUE THREAD

**Issue by shannonchou** [Weebly/TableSchemer#12]
Sorry, I did not find how to use nib cell throughout the documents.

**Comment by ketzusaka** [comment]
Hey Shannonchou,

No worries, I don't think we've got anything there. I'll add something in the docs shortly for the future, and also probably improve support for such a thing.

TableSchemer automatically registers classes to be used on instantiation. However, you can override the built-in class registration with your UINib; you'd just have to make sure you use the same identifier.

After you create your `TableScheme` you'd call something like this:

```
tableView.register(UINib(nibName: "Foo", bundle: nil), forCellReuseIdentifier: String(describing: Bar.self))
```

In that example, your nib is named `Foo` and the cell class is `Bar`. It is important to note that this must be called after you initialize the `TableScheme`; otherwise the built-in registration will replace your registration, instead of the other way around.

Let me know if you have any other questions!

**Comment by shannonchou** [comment]
Thanks for your immediate reply. I got it to work by following your detailed instructions.
